/** Verification State Machine & evidence-derived confidence engine. */
export type VerificationState = 'USER_CLAIM'|'MODEL_KNOWLEDGE'|'UNVERIFIED'|'SOURCE_FOUND'|'SOURCE_CHECKED'|'PARTIALLY_VERIFIED'|'VERIFIED'|'STALE'|'CONFLICTED';
export type EpistemicClass = 'FACT'|'MODEL_KNOWLEDGE'|'INFERENCE'|'HYPOTHESIS'|'SCENARIO'|'UNVERIFIED'|'DECISION_GAP';
export interface EvaluatedClaimState { claimId:string; claimText:string; epistemicClass:EpistemicClass; verificationState:VerificationState; sourceReliability:number|null; evidenceCoverage:number; evidenceQuality:number|null; recencyFactor:number; corroborationCount:number; conflictDetected:boolean; isStale:boolean; basedOnPremises?:string[]; auditTrail:string[]; }
export interface VerificationStateMachineInput { isTemporalSensitive:boolean; temporalRetrievalVerified:boolean; temporalAuthorityScore?:number; temporalAuthorityMeasured?:boolean; temporalEvidenceQuality?:number; temporalSourceTitle?:string; temporalSourceUrl?:string; rawSearchSources:Array<{id:string;source:string;authorityScore?:number;authorityMeasured?:boolean;isVerified?:boolean;publishedDate?:string;content?:string;qualityScore?:number;qualityMeasured?:boolean}>; attachments:Array<{id:string;name:string;quality?:number;qualityMeasured?:boolean}>; memories:Array<{id?:string;content:string;relevanceScore?:number;layer?:string}>; missingSignalsCount:number; conflictCount:number; isCutoffOutdated:boolean; }
export interface DeterministicConfidenceBreakdown { scorePercent:number|null; label:'สูง'|'ปานกลาง'|'ต่ำ'|'ไม่สามารถประเมินได้'; verificationState:VerificationState; evidenceCoverage:number; sourceReliability:number|null; evidenceQuality:number|null; recencyFactor:number; directnessScore:number; missingPenalty:number; conflictPenalty:number; mathematicalProof:string; formula:string; epistemicQuarantineActive:boolean; quarantineReason?:string; }
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const finite=(n:unknown):n is number=>typeof n==='number'&&Number.isFinite(n);
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
const measuredAuthority=(s:{authorityScore?:number;authorityMeasured?:boolean})=>s.authorityMeasured===true&&finite(s.authorityScore);
const measuredQuality=(s:{qualityScore?:number;qualityMeasured?:boolean})=>s.qualityMeasured===true&&finite(s.qualityScore);
export function transitionVerificationState(input:VerificationStateMachineInput){
 const missing=Math.max(0,input.missingSignalsCount||0),conflicts=Math.max(0,input.conflictCount||0),raw=(input.rawSearchSources||[]).filter(Boolean),attachments=(input.attachments||[]).filter(Boolean),memories=(input.memories||[]).filter(Boolean);
 if(conflicts>0){const verified=raw.filter(s=>s.isVerified&&measuredAuthority(s));return {state:'CONFLICTED' as VerificationState,sourceReliability:avg(verified.map(s=>clamp(s.authorityScore!))),evidenceCoverage:raw.length?clamp(1/(1+conflicts)):0,evidenceQuality:avg(raw.filter(measuredQuality).map(s=>clamp(s.qualityScore!))),recencyFactor:0,directnessScore:0.2,reason:'ตรวจพบหลักฐานที่มีความขัดแย้ง จึงกักกันข้อสรุปจนกว่าจะคลี่คลาย'};}
 if(input.isTemporalSensitive){
  if(input.temporalRetrievalVerified){const authority= input.temporalAuthorityMeasured===true&&finite(input.temporalAuthorityScore)?clamp(input.temporalAuthorityScore!):null,quality=finite(input.temporalEvidenceQuality)?clamp(input.temporalEvidenceQuality!):null;const coverage=clamp(1/(1+missing));const state=authority!==null&&quality!==null&&missing===0?'VERIFIED':'SOURCE_CHECKED';return {state:state as VerificationState,sourceReliability:authority,evidenceCoverage:coverage,evidenceQuality:quality,recencyFactor:1,directnessScore:1,reason:state==='VERIFIED'?'ยืนยันจากการ retrieval ข้อมูลปัจจุบันที่มี authority และ quality metadata ที่วัดได้':'retrieval ผ่าน แต่ยังมี measured metadata สำหรับ verification ไม่ครบ จึงไม่เลื่อนเป็น VERIFIED'};}
  return {state:(input.isCutoffOutdated?'STALE':raw.length?'SOURCE_FOUND':'UNVERIFIED') as VerificationState,sourceReliability:null,evidenceCoverage:0,evidenceQuality:null,recencyFactor:0,directnessScore:0,reason:'เป็นข้อมูลที่ขึ้นกับเวลาแต่ยังไม่มีหลักฐานปัจจุบันที่ยืนยันได้'};
 }
 if(attachments.length){const qualities=attachments.filter(a=>a.qualityMeasured===true).map(a=>a.quality).filter(finite).map(clamp),q=avg(qualities),coverage=clamp(1/(1+missing));if(q===null)return {state:'UNVERIFIED' as VerificationState,sourceReliability:null,evidenceCoverage:0,evidenceQuality:null,recencyFactor:0,directnessScore:0,reason:'พบเอกสาร แต่ไม่มี quality metadata ที่วัดได้อย่างชัดเจน จึงกักกันเป็น INSUFFICIENT_EVIDENCE'};return {state:'PARTIALLY_VERIFIED' as VerificationState,sourceReliability:null,evidenceCoverage:coverage,evidenceQuality:q,recencyFactor:1,directnessScore:1,reason:'เอกสารมี quality metadata ที่วัดได้ แต่ไม่มี source reliability metadata แยกต่างหาก จึงไม่เลื่อนเป็น VERIFIED'};}
 if(raw.length){const verified=raw.filter(s=>s.isVerified&&measuredAuthority(s));if(verified.length){const rel=avg(verified.map(s=>clamp(s.authorityScore!)))!,qualities=verified.filter(measuredQuality).map(s=>clamp(s.qualityScore!)),quality=avg(qualities),coverage=clamp(verified.length/Math.max(1,raw.length)),state=rel>=.85&&coverage>=.8&&missing===0&&quality!==null?'VERIFIED':'PARTIALLY_VERIFIED';return {state:state as VerificationState,sourceReliability:rel,evidenceCoverage:coverage,evidenceQuality:quality,recencyFactor:avg(verified.map(s=>s.publishedDate?1:0))!,directnessScore:coverage,reason:quality!==null?'มี source ที่ผ่าน verification และมี measured reliability/quality metadata แยกกัน':'มี source ที่ผ่าน verification แต่ยังไม่มี measured evidence quality metadata แยกจาก source reliability'};}return {state:'SOURCE_FOUND' as VerificationState,sourceReliability:null,evidenceCoverage:0,evidenceQuality:null,recencyFactor:0,directnessScore:0,reason:'พบ source แต่ยังไม่มี measured metadata ที่ยืนยันความน่าเชื่อถือ จึงไม่สร้างตัวเลข confidence'};}
 if(memories.some(m=>finite(m.relevanceScore)))return {state:'MODEL_KNOWLEDGE' as VerificationState,sourceReliability:null,evidenceCoverage:0,evidenceQuality:null,recencyFactor:0,directnessScore:0,reason:'มีเพียงบริบทภายใน ไม่มี external evidence'};
 return {state:'UNVERIFIED' as VerificationState,sourceReliability:null,evidenceCoverage:0,evidenceQuality:null,recencyFactor:0,directnessScore:0,reason:'ไม่มีหลักฐานเชิงประจักษ์ที่ตรวจสอบได้'};
}
export function computeDeterministicConfidence(t:ReturnType<typeof transitionVerificationState>,missingCount:number,conflictCount:number):DeterministicConfidenceBreakdown{
 const missing=Math.max(0,missingCount||0),conflicts=Math.max(0,conflictCount||0),missingPenalty=Number(Math.min(.35,missing*.05).toFixed(2)),conflictPenalty=Number(Math.min(.40,conflicts*.15).toFixed(2));
 const quarantined=['UNVERIFIED','STALE','MODEL_KNOWLEDGE','SOURCE_FOUND','CONFLICTED'].includes(t.state)||(t.state==='SOURCE_CHECKED'&&(t.sourceReliability===null||t.evidenceQuality===null))||(t.state==='PARTIALLY_VERIFIED'&&(t.sourceReliability===null||t.evidenceQuality===null))||(t.state==='VERIFIED'&&(t.sourceReliability===null||t.evidenceQuality===null));
 if(quarantined)return {scorePercent:null,label:'ไม่สามารถประเมินได้',verificationState:t.state,evidenceCoverage:t.evidenceCoverage,sourceReliability:t.sourceReliability,evidenceQuality:t.evidenceQuality,recencyFactor:t.recencyFactor,directnessScore:t.directnessScore,missingPenalty,conflictPenalty,formula:'N/A',mathematicalProof:`State=${t.state}; หลักฐานยังไม่ผ่าน verification จึงไม่คำนวณตัวเลข confidence.`,epistemicQuarantineActive:true,quarantineReason:'หลักฐานยังไม่ผ่าน verification จึงไม่สร้างตัวเลขความมั่นใจ'};
 if(t.state==='PARTIALLY_VERIFIED'||t.state==='SOURCE_CHECKED'){const base=t.evidenceCoverage*.35+t.sourceReliability!*.30+t.evidenceQuality!*.20+t.recencyFactor*.15,score=Math.round(clamp(base-missingPenalty-conflictPenalty)*100);return {scorePercent:score,label:score>=50?'ปานกลาง':'ต่ำ',verificationState:t.state,evidenceCoverage:t.evidenceCoverage,sourceReliability:t.sourceReliability,evidenceQuality:t.evidenceQuality,recencyFactor:t.recencyFactor,directnessScore:t.directnessScore,missingPenalty,conflictPenalty,formula:'Score = 0.35×Coverage + 0.30×Reliability + 0.20×Quality + 0.15×Recency − penalties',mathematicalProof:'Score is a deterministic function of supplied evidence metrics.',epistemicQuarantineActive:false};}
 if(t.state==='VERIFIED'){const base=t.evidenceCoverage*.30+t.sourceReliability!*.30+t.evidenceQuality!*.20+t.recencyFactor*.10+t.directnessScore*.10,score=Math.round(clamp(base-missingPenalty-conflictPenalty)*100);return {scorePercent:score,label:score>=75?'สูง':'ปานกลาง',verificationState:t.state,evidenceCoverage:t.evidenceCoverage,sourceReliability:t.sourceReliability,evidenceQuality:t.evidenceQuality,recencyFactor:t.recencyFactor,directnessScore:t.directnessScore,missingPenalty,conflictPenalty,formula:'Score = 0.30×Coverage + 0.30×Reliability + 0.20×Quality + 0.10×Recency + 0.10×Directness − penalties',mathematicalProof:`VERIFIED uses only supplied evidence metrics: ${[t.evidenceCoverage,t.sourceReliability,t.evidenceQuality,t.recencyFactor,t.directnessScore].map(v=>finite(v)?v.toFixed(2):'N/A').join(', ')}`,epistemicQuarantineActive:false};}
 return {scorePercent:null,label:'ไม่สามารถประเมินได้',verificationState:t.state,evidenceCoverage:t.evidenceCoverage,sourceReliability:t.sourceReliability,evidenceQuality:t.evidenceQuality,recencyFactor:t.recencyFactor,directnessScore:t.directnessScore,missingPenalty,conflictPenalty,formula:'N/A',mathematicalProof:'Undefined state',epistemicQuarantineActive:true};
}
